const stores = [
  {
    id: 1,
    name: "샐로리 한남점",
    rate: 4.9,
    reviewCnt: 3919,
    minDeliveryTime: 13,
    maxDeliveryTime: 30,
    payMethod : "토스 결제만 현장결제 안됨",
    deliveryTime : "약 15-25분",
    minDeliveryPrice: 13000,
    deliveryFee: 2000,
    menus: [
      {
        id: 1,
        name: "토마토 샐러드",
        category: "샐러드",
        isBest: true,
        price: 7600,
        ingredients: "계란, 옥수수, 양파, 올리브, 베이컨, 시저드레싱",
      },
      {
        id: 2,
        name: "시저 샐러드",
        category: "샐러드",
        isBest: false,
        price: 6900,
        ingredients: "로메인 상추와 크루통이며, 달걀, 올리브유, 레몬 즙, 마늘",
      },
      {
        id: 3,
        name: "리코타치즈 샐러드",
        category: "샐러드",
        isBest: false,
        price: 6900,
        ingredients: "리코타치즈, 양상추, 베이비채소, 방울토마톹, 블랙올리브",
      },
      {
        id: 4,
        name: "탄단지 샐러드",
        category: "샐러드",
        isBest: false,
        price: 7600,
        ingredients: "치킨, 고구마, 견과류, 크래배리, 오리엔탈",
      },
    ],
  },
  {
    id: 2,
    name: "그린가든 강남점",
    rate: 4.7,
    reviewCnt: 2451,
    minDeliveryTime: 15,
    maxDeliveryTime: 25,
    minDeliveryPrice: 12000,
    deliveryFee: 2500,
    menus: [
      {
        id: 1,
        name: "아보카도 그린 샐러드",
        category: "샐러드",
        isBest: true,
        price: 8900,
        ingredients: "아보카도, 케일, 시금치, 퀴노아, 레몬 드레싱",
      },
      {
        id: 2,
        name: "베리 믹스 샐러드",
        category: "샐러드",
        isBest: false,
        price: 8500,
        ingredients: "블루베리, 라즈베리, 스트로베리, 믹스 그린, 요거트 드레싱",
      },
    ],
  },
  {
    id: 3,
    name: "헬시키친 홍대입구",
    rate: 4.8,
    reviewCnt: 1784,
    minDeliveryTime: 20,
    maxDeliveryTime: 35,
    minDeliveryPrice: 10000,
    deliveryFee: 1500,
    menus: [
      {
        id: 1,
        name: "쿼리노아 비트 샐러드",
        category: "샐러드",
        isBest: true,
        price: 9200,
        ingredients: "비트, 쿼리노아, 아몬드, 양배추, 사과 사이더 드레싱",
      },
      {
        id: 2,
        name: "펌프킨 넛 샐러드",
        category: "샐러드",
        isBest: false,
        price: 8700,
        ingredients: "호박, 피칸, 크랜베리, 아루굴라, 발사믹 드레싱",
      },
    ],
  },
  {
    id: 4,
    name: "피자헛 강남점",
    rate: 4.5,
    reviewCnt: 3500,
    minDeliveryTime: 20,
    maxDeliveryTime: 40,
    minDeliveryPrice: 15000,
    deliveryFee: 3000,
    menus: [
      {
        id: 1,
        name: "불고기 피자",
        category: "피자",
        isBest: true,
        price: 21000,
        ingredients: "불고기, 치즈, 양파, 피망, 소스",
      },
      {
        id: 2,
        name: "콤비네이션 피자",
        category: "피자",
        isBest: false,
        price: 20000,
        ingredients: "치즈, 소시지, 양파, 피망, 올리브, 소스",
      },
    ],
  },
  {
    id: 5,
    name: "맥도날드 역삼점",
    rate: 4.3,
    reviewCnt: 2700,
    minDeliveryTime: 15,
    maxDeliveryTime: 30,
    minDeliveryPrice: 10000,
    deliveryFee: 2000,
    menus: [
      {
        id: 1,
        name: "빅맥",
        category: "버거",
        isBest: true,
        price: 5500,
        ingredients: "소고기 패티, 양상추, 치즈, 소스, 피클, 양파, 빵",
      },
      {
        id: 2,
        name: "맥치킨",
        category: "버거",
        isBest: false,
        price: 5000,
        ingredients: "치킨 패티, 양상추, 마요네즈, 빵",
      },
    ],
  },
  {
    id: 6,
    name: "한식당 청담점",
    rate: 4.8,
    reviewCnt: 3200,
    minDeliveryTime: 25,
    maxDeliveryTime: 45,
    minDeliveryPrice: 20000,
    deliveryFee: 3500,
    menus: [
      {
        id: 1,
        name: "불고기 정식",
        category: "한식",
        isBest: true,
        price: 15000,
        ingredients: "불고기, 밥, 반찬",
      },
      {
        id: 2,
        name: "비빔밥",
        category: "한식",
        isBest: false,
        price: 12000,
        ingredients: "밥, 나물, 고추장, 계란",
      },
    ],
  },
  {
    id: 7,
    name: "분식집 신림점",
    rate: 4.6,
    reviewCnt: 2000,
    minDeliveryTime: 10,
    maxDeliveryTime: 20,
    minDeliveryPrice: 8000,
    deliveryFee: 1000,
    menus: [
      {
        id: 1,
        name: "떡볶이",
        category: "분식",
        isBest: true,
        price: 5000,
        ingredients: "떡, 고추장, 어묵, 양배추",
      },
      {
        id: 2,
        name: "순대",
        category: "분식",
        isBest: false,
        price: 6000,
        ingredients: "순대, 소금, 간, 허파",
      },
    ],
  },
  {
    id: 8,
    name: "치킨집 압구정점",
    rate: 4.9,
    reviewCnt: 4500,
    minDeliveryTime: 20,
    maxDeliveryTime: 35,
    minDeliveryPrice: 15000,
    deliveryFee: 2500,
    menus: [
      {
        id: 1,
        name: "후라이드 치킨",
        category: "치킨",
        isBest: true,
        price: 18000,
        ingredients: "닭고기, 튀김가루, 소금",
      },
      {
        id: 2,
        name: "양념 치킨",
        category: "치킨",
        isBest: false,
        price: 19000,
        ingredients: "닭고기, 양념 소스, 튀김가루",
      },
    ],
  },
  {
    id: 9,
    name: "스시집 서초점",
    rate: 4.7,
    reviewCnt: 3000,
    minDeliveryTime: 30,
    maxDeliveryTime: 50,
    minDeliveryPrice: 25000,
    deliveryFee: 4000,
    menus: [
      {
        id: 1,
        name: "연어 스시",
        category: "스시",
        isBest: true,
        price: 12000,
        ingredients: "연어, 밥, 간장, 와사비",
      },
      {
        id: 2,
        name: "참치 스시",
        category: "스시",
        isBest: false,
        price: 13000,
        ingredients: "참치, 밥, 간장, 와사비",
      },
    ],
  },
  {
    id: 10,
    name: "서브웨이 이태원점",
    rate: 4.4,
    reviewCnt: 2200,
    minDeliveryTime: 15,
    maxDeliveryTime: 25,
    minDeliveryPrice: 10000,
    deliveryFee: 2000,
    menus: [
      {
        id: 1,
        name: "이탈리안 비엠티",
        category: "샌드위치",
        isBest: true,
        price: 7000,
        ingredients: "햄, 살라미, 치즈, 야채, 소스, 빵",
      },
      {
        id: 2,
        name: "써브웨이 클럽",
        category: "샌드위치",
        isBest: false,
        price: 7500,
        ingredients: "터키, 햄, 베이컨, 치즈, 야채, 소스, 빵",
      },
    ],
  },
  {
    id: 11,
    name: "파스타집 대치점",
    rate: 4.6,
    reviewCnt: 2500,
    minDeliveryTime: 25,
    maxDeliveryTime: 40,
    minDeliveryPrice: 20000,
    deliveryFee: 3000,
    menus: [
      {
        id: 1,
        name: "알리오 올리오",
        category: "파스타",
        isBest: true,
        price: 13000,
        ingredients: "스파게티, 올리브 오일, 마늘, 고추",
      },
      {
        id: 2,
        name: "까르보나라",
        category: "파스타",
        isBest: false,
        price: 15000,
        ingredients: "스파게티, 크림, 베이컨, 치즈, 달걀 노른자",
      },
    ],
  },
  {
    id: 12,
    name: "디저트샵 명동점",
    rate: 4.8,
    reviewCnt: 2800,
    minDeliveryTime: 10,
    maxDeliveryTime: 20,
    minDeliveryPrice: 5000,
    deliveryFee: 1000,
    menus: [
      {
        id: 1,
        name: "초콜릿 케이크",
        category: "디저트",
        isBest: true,
        price: 7000,
        ingredients: "초콜릿, 밀가루, 계란, 설탕, 버터",
      },
      {
        id: 2,
        name: "치즈 케이크",
        category: "디저트",
        isBest: false,
        price: 8000,
        ingredients: "크림치즈, 밀가루, 계란, 설탕, 버터",
      },
    ],
  },
  {
    id: 13,
    name: "커피숍 홍대점",
    rate: 4.9,
    reviewCnt: 3000,
    minDeliveryTime: 15,
    maxDeliveryTime: 25,
    minDeliveryPrice: 5000,
    deliveryFee: 1000,
    menus: [
      {
        id: 1,
        name: "아메리카노",
        category: "커피",
        isBest: true,
        price: 4000,
        ingredients: "에스프레소, 물",
      },
      {
        id: 2,
        name: "카페 라떼",
        category: "커피",
        isBest: false,
        price: 4500,
        ingredients: "에스프레소, 우유",
      },
      {
        id: 3,
        name: "카푸치노",
        category: "커피",
        isBest: false,
        price: 4500,
        ingredients: "에스프레소, 우유, 거품",
      },
    ],
  },
  {
    id: 14,
    name: "커피빈 강남점",
    rate: 4.8,
    reviewCnt: 2500,
    minDeliveryTime: 10,
    maxDeliveryTime: 20,
    minDeliveryPrice: 5000,
    deliveryFee: 1000,
    menus: [
      {
        id: 1,
        name: "콜드 브루",
        category: "커피",
        isBest: true,
        price: 5000,
        ingredients: "콜드 브루 커피",
      },
      {
        id: 2,
        name: "모카",
        category: "커피",
        isBest: false,
        price: 5000,
        ingredients: "에스프레소, 초콜릿 시럽, 우유",
      },
      {
        id: 3,
        name: "바닐라 라떼",
        category: "커피",
        isBest: false,
        price: 5500,
        ingredients: "에스프레소, 우유, 바닐라 시럽",
      },
    ],
  },
];

export default stores;
