const stores = [
  {
    id: 1,
    name: "샐로리 한남점",
    rate: 4.9,
    reviewCnt: 3919,
    minDeliveryTime: 13,
    maxDeliveryTime: 30,
    minDeliveryPrice: 13000,
    deliveryFee: 2000,
    menus: [
      {
        id: 1,
        storeId: 1,
        name: "토마토 샐러드",
        isBest: true,
        price: 7600,
        ingredients: "계란, 옥수수, 양파, 올리브, 베이컨, 시저드레싱",
        quantity:0,
      },
      {
        id: 2,
        storeId: 1,
        name: "시저 샐러드",
        isBest: false,
        price: 6900,
        ingredients: "로메인 상추와 크루통이며, 달걀, 올리브유, 레몬 즙, 마늘",
        quantity:0,
      },
      {
        id: 3,
        storeId: 1,
        name: "리코타치즈 샐러드",
        isBest: false,
        price: 6900,
        ingredients: "리코타치즈, 양상추, 베이비채소, 방울토마톹, 블랙올리브",
        quantity:0,
      },
      {
        id: 4,
        storeId: 1,
        name: "탄단지 샐러드",
        isBest: false,
        price: 7600,
        ingredients: "치킨, 고구마, 견과류, 크래배리, 오리엔탈",
        quantity:0,
      },
    ],
  },
  {
    id: 2,
    name: "그린가든 강남점",
    rate: 4.7,
    reviewCnt: 2451,
    minDeliveryTime: 15,
    maxDeliveryTime: 25,
    minDeliveryPrice: 12000,
    deliveryFee: 2500,
    menus: [
      {
        id: 1,
        storeId: 2,
        name: "아보카도 그린 샐러드",
        isBest: true,
        price: 8900,
        ingredients: "아보카도, 케일, 시금치, 퀴노아, 레몬 드레싱",

      },
      {
        id: 2,
        storeId: 2,
        name: "베리 믹스 샐러드",
        isBest: false,
        price: 8500,
        ingredients: "블루베리, 라즈베리, 스트로베리, 믹스 그린, 요거트 드레싱",

      },
    ],
  },
  {
    id: 3,
    name: "헬시키친 홍대입구",
    rate: 4.8,
    reviewCnt: 1784,
    minDeliveryTime: 20,
    maxDeliveryTime: 35,
    minDeliveryPrice: 10000,
    deliveryFee: 1500,
    menus: [
      {
        id: 1,
        storeId: 3,
        name: "쿼리노아 비트 샐러드",
        isBest: true,
        price: 9200,
        ingredients: "비트, 쿼리노아, 아몬드, 양배추, 사과 사이더 드레싱",

      },
      {
        id: 2,
        storeId: 3,
        name: "펌프킨 넛 샐러드",
        isBest: false,
        price: 8700,
        ingredients: "호박, 피칸, 크랜베리, 아루굴라, 발사믹 드레싱",

      },
    ],
  },
  {
    id: 4,
    name: "씬더볼드 한남점",
    rate: 4.8,
    reviewCnt: 919,
    minDeliveryTime: 13,
    maxDeliveryTime: 30,
    minDeliveryPrice: 12000,
    deliveryFee: 2000,
    menus: [
      {
        id: 1,
        storeId: 4,
        name: "파스타 샐러드",
        isBest: true,
        price: 12900,
        ingredients: "파스타, 올리브, 체리 토마토, 모짜렐라 치즈, 바질, 올리브 오일, 발사믹 식초",

      },
      {
        id: 2,
        storeId: 4,
        name: "니수아즈 샐러드",
        isBest: false,
        price: 13500,
        ingredients: "참치, 감자, 그린빈, 올리브, 삶은 달걀, 토마토, 앤초비, 올리브 오일, 식초",

      },
    ],
  },
  {
    id: 5,
    name: "THE 샐러드가득담은",
    rate: 5.0,
    reviewCnt: 27,
    minDeliveryTime: 13,
    maxDeliveryTime: 30,
    minDeliveryPrice: 12000,
    deliveryFee: 2000,
    menus: [
      {
        id: 1,
        storeId: 5,
        name: "퀴노아 샐러드",
        isBest: true,
        price: 11000,
        ingredients: "퀴노아, 병아리콩, 오이, 토마토, 고수, 레몬 주스, 올리브 오일",
 
      },
      {
        id: 2,
        storeId: 5,
        name: "닭고기 샐러드",
        isBest: false,
        price: 9900,
        ingredients: "닭가슴살, 셀러리, 마요네즈, 양파, 소금, 후추, 각종 허브",

      },
    ],
  },
  {
    id: 6,
    name: "파스트보이",
    rate: 4.8,
    reviewCnt: 801,
    minDeliveryTime: 13,
    maxDeliveryTime: 30,
    minDeliveryPrice: 10000,
    deliveryFee: 2000,
    menus: [
      {
        id: 1,
        storeId: 6,
        name: "카프레제 샐러드",
        isBest: false,
        price: 8900,
        ingredients: "토마토, 모짜렐라 치즈, 바질, 올리브 오일, 발사믹 식초, 소금, 후추",
      },
      {
        id: 2,
        storeId: 6,
        name: "베리 믹스 샐러드",
        isBest: true,
        price: 7500,
        ingredients: "블루베리, 라즈베리, 스트로베리, 믹스 그린, 요거트 드레싱",

      },
      {
        id: 3,
        storeId: 6,
        name: "코올슬로",
        isBest: false,
        price: 4000,
        ingredients: "양배추, 당근, 마요네즈, 식초, 설탕, 소금, 후추",

      },
    ],
  },
];

export default stores;
